version: '3.9'

services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "9191:9191"
    depends_on:
      - orders-db
    networks:
      - app_network

  order-poller:
    build:
      context: ./order-poller
    ports:
      - "9292:9292"
    depends_on:
      - orders-db
      - broker
    networks:
      - app_network

  orders-db:
    image: postgres:15
    container_name: orders-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders-endterm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
      - orders-data:/var/lib/postgresql/data
    networks:
      - app_network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
      - orders-db


networks:
  app_network:
    driver: bridge

volumes:
  orders-data:
